### ISSUE TITLE
Allow for lorem ipsum.

### ISSUE THREAD

**Issue by lukasoppermann** [Tallwave/sketch-spellcheck-all-layers#15]
While it is no real text, I feel it is distinct enough to be recognisable. Otherwise the spellchecker chokes up on hundreds of fake-latin words.

**Comment by seanriceaz** [comment]
I've been encountering this a lot right now as well.

A couple workarounds for the time being:

- Use an english based lorem ipsum generator (like hipster ipsum, or bacon ipsum, etc)
- Use the "Ignore All" button. It's a pain the first time you use it in a session, but after that, the spellchecker ignores it.
