### ISSUE TITLE
Plugin not working after updating Sketch

### ISSUE THREAD

**Issue by dnice2288** [Tallwave/sketch-spellcheck-all-layers#20]
I did an update today (6/28/17) to Sketch version 45 (43475) and the spell check plugin does not work anymore.

**Comment by seanriceaz** [comment]
Bah! They deprecated a function I was using. It's cool though, I fixed it (as soon as my PR gets merged in...) If you're in a hurry, download my version here: https://github.com/seanriceaz/sketch-spellcheck-all-layers/archive/master.zip

**Comment by seanriceaz** [comment]
This has been resolved. Please download the latest from here (I also just added auto-update support!): https://github.com/Tallwave/sketch-spellcheck-all-layers/archive/master.zip
