### ISSUE TITLE
Feature Request: Count of errors, like (1/23)

### ISSUE THREAD

**Issue by jrbondesign** [Tallwave/sketch-spellcheck-all-layers#28]
Great plugin! Just a suggestion to help know how many errors and when/if it loops around. Thanks!

**Comment by seanriceaz** [comment]
It should be doing this. There appears to be a bug with the little popup that used to appear. Might be that Sketch deprecated it and I need to update :\

**Comment by seanriceaz** [comment]
Fixed with 1.3.1
