### ISSUE TITLE
No notification its running, no results with intentionally misspelled words

### ISSUE THREAD

**Issue by moderntarra** [Tallwave/sketch-spellcheck-all-layers#29]
There's basically nothing happening. Any help?

**Comment by Rmohan06** [comment]
Finding that the plugin only works sometimes with no indication that the spell check runs. I also intentionally misspelled words that the plugin misses.

**Comment by seanriceaz** [comment]
I'm pretty surprised by this. Can you upload your debug logs somewhere I can get to them?

Is this still happening to you?

**Comment by seanriceaz** [comment]
This was a problem with a little notification that wasn't showing up anymore. Should be fixed as of 1.3.1.

**Comment by Rmohan06** [comment]
Yep - looks like it’s working now! Thanks for taking care of this.

Rob
