### ISSUE TITLE
Hability to change language

### ISSUE THREAD

**Issue by qwervo** [Tallwave/sketch-spellcheck-all-layers#31]
Hi. It would be grat if you coul change the language.

**Comment by seanriceaz** [comment]
Do you mean that you'd like the dialog to be localized? Or that it's only spell checking on the English language?

It *should* be using your system dictionary for spell checking.  Is this not the case?

**Comment by seanriceaz** [comment]
This is related to #35 I think they're duplicate issues, so I'm closing this one out.
