### ISSUE TITLE
Cannot dismiss dialog

### ISSUE THREAD

**Issue by cpshanley** [Tallwave/sketch-spellcheck-all-layers#36]
It checks all pages in the document, not just the current one.

Pressing the Done button in the dialog does not terminate the operation - it just keeps on spell-checking. This is a big problem if lorem ipsum text is included on other pages.

**Comment by seanriceaz** [comment]
Verified that this is an issue.

**Comment by seanriceaz** [comment]
This should work again as of 1.3.2
